name: loja_p2
description: "Loja E-commerce"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Navegação e estado
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1

  # REST e modelos
  dio: ^5.7.0
  retrofit: ^4.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Firebase 
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # Sessão local 
  shared_preferences: ^2.3.2

  translator: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  retrofit_generator: ^9.7.0
  json_serializable: ^6.8.0


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
